name: Sync Leetcode

on:
  workflow_dispatch:      # Allows you to trigger the sync manually with a button
  schedule:
    - cron: "0 8 * * 6"   # Automatically runs every Saturday at 8:00 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
